# Author: Baylee Christensen
# Date: 10/12/204
# Description: This R script passes in arguments from 04_matrixify.sh, grabs the sample_info spreadsheet (which contains information about tissue type and individuals), adds a new column indicating type of gene, and saves updated data to a new csv file with '_updated'



# Get the file paths from the command-line arguments
args <- commandArgs(trailingOnly = TRUE)
# The combined_variants_path is passed from bash script as input file, and if not provided, defaults to 'combined_varaints.csv'
combined_variants_path <- ifelse(length(args) > 0, args[1], "combined_variants.csv")
# The output updated_variants_path is generated by appending _updated to the file name
updated_variants_path <- sub(".csv", "_updated.csv", combined_variants_path)  # Automatically create an updated file name

# Load the CSV files
combined_variants <- read.csv(combined_variants_path, stringsAsFactors = FALSE)

sample_info_path <- "/scratch/general/nfs1/utu_4310/whiptail_dge_working_directory/matrix/sample_info.csv"
sample_info <- read.csv(sample_info_path, stringsAsFactors = FALSE)  

# Merge data based on SampleID and add the GeneType column
merged_data <- merge(combined_variants, sample_info, by = "SampleID", all.x = TRUE)
merged_data$GeneType <- ifelse(is.na(merged_data$Gene), "Other", "Mito")

# Write the updated data to a CSV file
write.csv(merged_data, updated_variants_path, row.names = FALSE)
